### ISSUE TITLE
PPP Loan Options Content

### ISSUE THREAD

**Issue by dylanenright** [usdigitalresponse/small-business-programs#17]
https://docs.google.com/document/d/1BeTkI10e0nwEPgMOXPGLH2DOy5L61M2rTgtu3QIZf2E/edit#

@jasimon should have the html file to make standalone page. Could probably use @jrubenoff help to make it look decent.

Great edits from @jrubenoff. @dylanenright to update html.

**Comment by jrubenoff** [comment]
Just revised the copy in the doc as per [plain language](https://www.plainlanguage.gov/) guidelines.

I also tried to standardize the language we use for each bank, so that we could more easily abstract this to JSON / YAML / etc. when we move beyond static HTML.

@jasimon I was thinking we could let users sort the first 2 table columns  alphabetically, so that you could immediately see which banks were accepting applications from everyone. Let me know what you think.

**Comment by jasimon** [comment]
@jrubenoff I like the idea but that may be something better left post-React?  I could write custom js on the page but would be brittle for older browsers.
